// Copyright (c) 2014-2020 DataStax Inc.
// Copyright (c) 2020, Rafael Almeida (ralmsdevelper)
// Licensed under the Apache License, Version 2.0. See LICENCE in the project root for license information.

using System;

namespace Scylla.Net
{
    [Flags]
    internal enum HeaderFlags : byte
    {
        None = 0,

        /// <summary>
        /// If set, the frame body is compressed.
        /// </summary>
        Compression = 0x01,

        /// <summary>
        /// For a request frame, this indicate the client requires tracing of the request.
        /// If a response frame has the tracing flag set, its body contains a tracing ID.
        /// </summary>
        Tracing = 0x02,

        /// <summary>
        /// For a request or response frame, this indicates that generic key-value 
        /// custom payload for a custom QueryHandler implementation is present in the frame.
        /// </summary>
        CustomPayload = 0x04,

        /// <summary>
        /// The response contains warnings from the server which 
        /// were generated by the server to go along with this response.
        /// </summary>
        Warning = 0x08,
        
        /// <summary>
        /// Indicates that the client opts in to use protocol version
        /// that is currently in beta. Server will respond with ERROR if protocol
        /// version is marked as beta on server and client does not provide this flag.
        /// </summary>
        UseBeta = 0x10
    }
}
